module DataType
  STX = 0x02
  KEY = 0x06
  KEYDATA = 0x00
  ETX = 0x03
end

module DataTag
  RELOJ_DE_PARTIDO_CON_DECIMAS_OPCIONALES = 0x11
  RELOJ_DE_PARTIDO_CON_SEGUNDOS_OPCIONALES = 0x12
  RELOJ_DE_POSESION = 0x13
  PERIODO = 0x15
  RELOJ_REAL = 0x16
  PUNTOS_LOCAL = 0x17
  PUNTOS_VISITANTE = 0x1F
  NUMERO_DE_FALTAS_DE_EQUIPO_LOCAL = 0x0E
  NUMERO_DE_FALTAS_DE_EQUIPO_VISITANTE = 0x0F
  ESTADISTICAS_JUGADOR = 0x1C
    ASIGNACION_INICIAL_DE_DORSALES = 0x1A
    FALTAS = 0x1D
    PUNTOS = 0x1E
    JUGADOR_EN_PISTA = 0x1F
    LOCAL = 0x30
    VISITANTE = 0x31
  ACTIVACION_BOCINA = 0x07
  APAGADO_DISPLAY_DE_POSESION = 0x127
  ENCENDIDO_RELOJ = 0x19
  PARADA_RELOJ = 0x1A
  ENCENDIDO_RELOJ_POSESION = 0x1B
  PARADA_RELOJ_POSESION = 0x14

end

module DataTagOffset
  RELOJ_DE_PARTIDO_CON_DECIMAS_OPCIONALES = 8
  RELOJ_DE_PARTIDO_CON_SEGUNDOS_OPCIONALES = 8
  RELOJ_DE_POSESION = 4
  PERIODO = 1
  RELOJ_REAL = 8
  PUNTOS_LOCAL = 3
  PUNTOS_VISITANTE = 3
  NUMERO_DE_FALTAS_DE_EQUIPO_LOCAL = 2
  NUMERO_DE_FALTAS_DE_EQUIPO_VISITANTE = 2

  LOCAL = 0x30
  VISITANTE = 0x31

  # ESTADISTICAS_JUGADOR = 0x1C
  #   ASIGNACION_INICIAL_DE_DORSALES = 0x1A
    FALTAS = 5
    PUNTOS = 5
    JUGADOR_EN_PISTA = 5

  ACTIVACION_BOCINA = 8
  # APAGADO_DISPLAY_DE_POSESION = 0x127 TODO ??
  ENCENDIDO_RELOJ = 8
  PARADA_RELOJ = 8
  ENCENDIDO_RELOJ_POSESION = 8
  PARADA_RELOJ_POSESION = 8

end